from app.styles.schemas import StyleItem

ads_styles = [
	StyleItem(
		id='ads_advertising',
		name='Ads Advertising',
		origin='Fooocus',
		positive='advertising poster style {prompt} . Professional, modern, product-focused, commercial, eye-catching, highly detailed',
		negative='noisy, blurry, amateurish, sloppy, unattractive',
		image='styles/ads/advertising.jpg',
	),
	StyleItem(
		id='ads_automotive',
		name='Ads Automotive',
		origin='Fooocus',
		positive='automotive advertisement style {prompt} . sleek, dynamic, professional, commercial, vehicle-focused, high-resolution, highly detailed',
		negative='noisy, blurry, unattractive, sloppy, unprofessional',
		image='styles/ads/automotive.jpg',
	),
	StyleItem(
		id='ads_corporate',
		name='Ads Corporate',
		origin='Fooocus',
		positive='corporate branding style {prompt} . professional, clean, modern, sleek, minimalist, business-oriented, highly detailed',
		negative='noisy, blurry, grungy, sloppy, cluttered, disorganized',
		image='styles/ads/corporate.jpg',
	),
	StyleItem(
		id='ads_fashion-editorial',
		name='Ads Fashion Editorial',
		origin='Fooocus',
		positive='fashion editorial style {prompt} . high fashion, trendy, stylish, editorial, magazine style, professional, highly detailed',
		negative='outdated, blurry, noisy, unattractive, sloppy',
		image='styles/ads/fashion-editorial.jpg',
	),
	StyleItem(
		id='ads_food-photography',
		name='Ads Food Photography',
		origin='Fooocus',
		positive='food photography style {prompt} . appetizing, professional, culinary, high-resolution, commercial, highly detailed',
		negative='unappetizing, sloppy, unprofessional, noisy, blurry',
		image='styles/ads/food-photography.jpg',
	),
	StyleItem(
		id='ads_gourmet-food-photography',
		name='Ads Gourmet Food Photography',
		origin='Fooocus',
		positive='gourmet food photo of {prompt} . soft natural lighting, macro details, vibrant colors, fresh ingredients, glistening textures, bokeh background, styled plating, wooden tabletop, garnished, tantalizing, editorial quality',
		negative='cartoon, anime, sketch, grayscale, dull, overexposed, cluttered, messy plate, deformed',
		image='styles/ads/gourmet-food-photography.jpg',
	),
	StyleItem(
		id='ads_luxury',
		name='Ads Luxury',
		origin='Fooocus',
		positive='luxury product style {prompt} . elegant, sophisticated, high-end, luxurious, professional, highly detailed',
		negative='cheap, noisy, blurry, unattractive, amateurish',
		image='styles/ads/luxury.jpg',
	),
	StyleItem(
		id='ads_real-estate',
		name='Ads Real Estate',
		origin='Fooocus',
		positive='real estate photography style {prompt} . professional, inviting, well-lit, high-resolution, property-focused, commercial, highly detailed',
		negative='dark, blurry, unappealing, noisy, unprofessional',
		image='styles/ads/real-estate.jpg',
	),
	StyleItem(
		id='ads_retail',
		name='Ads Retail',
		origin='Fooocus',
		positive='retail packaging style {prompt} . vibrant, enticing, commercial, product-focused, eye-catching, professional, highly detailed',
		negative='noisy, blurry, amateurish, sloppy, unattractive',
		image='styles/ads/retail.jpg',
	),
]
