from app.styles.schemas import StyleItem

artstyle_styles = [
	StyleItem(
		id='artstyle_abstract',
		name='Artstyle Abstract',
		origin='Fooocus',
		positive='abstract style {prompt} . non-representational, colors and shapes, expression of feelings, imaginative, highly detailed',
		negative='realistic, photographic, figurative, concrete',
		image='styles/artstyle/abstract.jpg',
	),
	StyleItem(
		id='artstyle_abstract-expressionism',
		name='Artstyle Abstract Expressionism',
		origin='Fooocus',
		positive='abstract expressionist painting {prompt} . energetic brushwork, bold colors, abstract forms, expressive, emotional',
		negative='realistic, photorealistic, low contrast, plain, simple, monochrome',
		image='styles/artstyle/abstract-expressionism.jpg',
	),
	StyleItem(
		id='artstyle_art-deco',
		name='Artstyle Art Deco',
		origin='Fooocus',
		positive='art deco style {prompt} . geometric shapes, bold colors, luxurious, elegant, decorative, symmetrical, ornate, detailed',
		negative='ugly, deformed, noisy, blurry, low contrast, realism, photorealistic, modernist, minimalist',
		image='styles/artstyle/art-deco.jpg',
	),
	StyleItem(
		id='artstyle_art-nouveau',
		name='Artstyle Art Nouveau',
		origin='Fooocus',
		positive='art nouveau style {prompt} . elegant, decorative, curvilinear forms, nature-inspired, ornate, detailed',
		negative='ugly, deformed, noisy, blurry, low contrast, realism, photorealistic, modernist, minimalist',
		image='styles/artstyle/art-nouveau.jpg',
	),
	StyleItem(
		id='artstyle_constructivist',
		name='Artstyle Constructivist',
		origin='Fooocus',
		positive='constructivist style {prompt} . geometric shapes, bold colors, dynamic composition, propaganda art style',
		negative='realistic, photorealistic, low contrast, plain, simple, abstract expressionism',
		image='styles/artstyle/constructivist.jpg',
	),
	StyleItem(
		id='artstyle_cubist',
		name='Artstyle Cubist',
		origin='Fooocus',
		positive='cubist artwork {prompt} . geometric shapes, abstract, innovative, revolutionary',
		negative='anime, photorealistic, 35mm film, deformed, glitch, low contrast, noisy',
		image='styles/artstyle/cubist.jpg',
	),
	StyleItem(
		id='artstyle_expressionist',
		name='Artstyle Expressionist',
		origin='Fooocus',
		positive='expressionist {prompt} . raw, emotional, dynamic, distortion for emotional effect, vibrant, use of unusual colors, detailed',
		negative='realism, symmetry, quiet, calm, photo',
		image='styles/artstyle/expressionist.jpg',
	),
	StyleItem(
		id='artstyle_graffiti',
		name='Artstyle Graffiti',
		origin='Fooocus',
		positive='graffiti style {prompt} . street art, vibrant, urban, detailed, tag, mural',
		negative='ugly, deformed, noisy, blurry, low contrast, realism, photorealistic',
		image='styles/artstyle/graffiti.jpg',
	),
	StyleItem(
		id='artstyle_hyperrealism',
		name='Artstyle Hyperrealism',
		origin='Fooocus',
		positive='hyperrealistic art {prompt} . extremely high-resolution details, photographic, realism pushed to extreme, fine texture, incredibly lifelike',
		negative='simplified, abstract, unrealistic, impressionistic, low resolution',
		image='styles/artstyle/hyperrealism.jpg',
	),
	StyleItem(
		id='artstyle_impressionist',
		name='Artstyle Impressionist',
		origin='Fooocus',
		positive='impressionist painting {prompt} . loose brushwork, vibrant color, light and shadow play, captures feeling over form',
		negative='anime, photorealistic, 35mm film, deformed, glitch, low contrast, noisy',
		image='styles/artstyle/impressionist.jpg',
	),
	StyleItem(
		id='artstyle_pointillism',
		name='Artstyle Pointillism',
		origin='Fooocus',
		positive='pointillism style {prompt} . composed entirely of small, distinct dots of color, vibrant, highly detailed',
		negative='line drawing, smooth shading, large color fields, simplistic',
		image='styles/artstyle/pointillism.jpg',
	),
	StyleItem(
		id='artstyle_pop-art',
		name='Artstyle Pop Art',
		origin='Fooocus',
		positive='pop Art style {prompt} . bright colors, bold outlines, popular culture themes, ironic or kitsch',
		negative='ugly, deformed, noisy, blurry, low contrast, realism, photorealistic, minimalist',
		image='styles/artstyle/pop-art.jpg',
	),
	StyleItem(
		id='artstyle_psychedelic',
		name='Artstyle Psychedelic',
		origin='Fooocus',
		positive='psychedelic style {prompt} . vibrant colors, swirling patterns, abstract forms, surreal, trippy',
		negative='monochrome, black and white, low contrast, realistic, photorealistic, plain, simple',
		image='styles/artstyle/psychedelic.jpg',
	),
	StyleItem(
		id='artstyle_renaissance',
		name='Artstyle Renaissance',
		origin='Fooocus',
		positive='renaissance style {prompt} . realistic, perspective, light and shadow, religious or mythological themes, highly detailed',
		negative='ugly, deformed, noisy, blurry, low contrast, modernist, minimalist, abstract',
		image='styles/artstyle/renaissance.jpg',
	),
	StyleItem(
		id='artstyle_steampunk',
		name='Artstyle Steampunk',
		origin='Fooocus',
		positive='steampunk style {prompt} . antique, mechanical, brass and copper tones, gears, intricate, detailed',
		negative='deformed, glitch, noisy, low contrast, anime, photorealistic',
		image='styles/artstyle/steampunk.jpg',
	),
	StyleItem(
		id='artstyle_surrealist',
		name='Artstyle Surrealist',
		origin='Fooocus',
		positive='surrealist art {prompt} . dreamlike, mysterious, provocative, symbolic, intricate, detailed',
		negative='anime, photorealistic, realistic, deformed, glitch, noisy, low contrast',
		image='styles/artstyle/surrealist.jpg',
	),
	StyleItem(
		id='artstyle_typography',
		name='Artstyle Typography',
		origin='Fooocus',
		positive='typographic art {prompt} . stylized, intricate, detailed, artistic, text-based',
		negative='ugly, deformed, noisy, blurry, low contrast, realism, photorealistic',
		image='styles/artstyle/typography.jpg',
	),
	StyleItem(
		id='artstyle_watercolor',
		name='Artstyle Watercolor',
		origin='Fooocus',
		positive='watercolor painting {prompt} . vibrant, beautiful, painterly, detailed, textural, artistic',
		negative='anime, photorealistic, 35mm film, deformed, glitch, low contrast, noisy',
		image='styles/artstyle/watercolor.jpg',
	),
]
