from app.styles.schemas import StyleItem

futuristic_styles = [
	StyleItem(
		id='futuristic_biomechanical',
		name='Futuristic Biomechanical',
		origin='Fooocus',
		positive='biomechanical style {prompt} . blend of organic and mechanical elements, futuristic, cybernetic, detailed, intricate',
		negative='natural, rustic, primitive, organic, simplistic',
		image='styles/futuristic/biomechanical.jpg',
	),
	StyleItem(
		id='futuristic_biomechanical-cyberpunk',
		name='Futuristic Biomechanical Cyberpunk',
		origin='Fooocus',
		positive='biomechanical cyberpunk {prompt} . cybernetics, human-machine fusion, dystopian, organic meets artificial, dark, intricate, highly detailed',
		negative='natural, colorful, deformed, sketch, low contrast, watercolor',
		image='styles/futuristic/biomechanical-cyberpunk.jpg',
	),
	StyleItem(
		id='futuristic_cybernetic',
		name='Futuristic Cybernetic',
		origin='Fooocus',
		positive='cybernetic style {prompt} . futuristic, technological, cybernetic enhancements, robotics, artificial intelligence themes',
		negative='ugly, deformed, noisy, blurry, low contrast, realism, photorealistic, historical, medieval',
		image='styles/futuristic/cybernetic.jpg',
	),
	StyleItem(
		id='futuristic_cybernetic-robot',
		name='Futuristic Cybernetic Robot',
		origin='Fooocus',
		positive='cybernetic robot {prompt} . android, AI, machine, metal, wires, tech, futuristic, highly detailed',
		negative='organic, natural, human, sketch, watercolor, low contrast',
		image='styles/futuristic/cybernetic-robot.jpg',
	),
	StyleItem(
		id='futuristic_cyberpunk-cityscape',
		name='Futuristic Cyberpunk Cityscape',
		origin='Fooocus',
		positive='cyberpunk cityscape {prompt} . neon lights, dark alleys, skyscrapers, futuristic, vibrant colors, high contrast, highly detailed',
		negative='natural, rural, deformed, low contrast, black and white, sketch, watercolor',
		image='styles/futuristic/cyberpunk-cityscape.jpg',
	),
	StyleItem(
		id='futuristic_futuristic',
		name='Futuristic Futuristic',
		origin='Fooocus',
		positive='futuristic style {prompt} . sleek, modern, ultramodern, high tech, detailed',
		negative='ugly, deformed, noisy, blurry, low contrast, realism, photorealistic, vintage, antique',
		image='styles/futuristic/futuristic.jpg',
	),
	StyleItem(
		id='futuristic_retro-cyberpunk',
		name='Futuristic Retro Cyberpunk',
		origin='Fooocus',
		positive='retro cyberpunk {prompt} . 80\'s inspired, synthwave, neon, vibrant, detailed, retro futurism',
		negative='modern, desaturated, black and white, realism, low contrast',
		image='styles/futuristic/retro-cyberpunk.jpg',
	),
	StyleItem(
		id='futuristic_retro-futurism',
		name='Futuristic Retro Futurism',
		origin='Fooocus',
		positive='retro-futuristic {prompt} . vintage sci-fi, 50s and 60s style, atomic age, vibrant, highly detailed',
		negative='contemporary, realistic, rustic, primitive',
		image='styles/futuristic/retro-futurism.jpg',
	),
	StyleItem(
		id='futuristic_sci-fi',
		name='Futuristic Sci Fi',
		origin='Fooocus',
		positive='sci-fi style {prompt} . futuristic, technological, alien worlds, space themes, advanced civilizations',
		negative='ugly, deformed, noisy, blurry, low contrast, realism, photorealistic, historical, medieval',
		image='styles/futuristic/sci-fi.jpg',
	),
	StyleItem(
		id='futuristic_vaporwave',
		name='Futuristic Vaporwave',
		origin='Fooocus',
		positive='vaporwave style {prompt} . retro aesthetic, cyberpunk, vibrant, neon colors, vintage 80s and 90s style, highly detailed',
		negative='monochrome, muted colors, realism, rustic, minimalist, dark',
		image='styles/futuristic/vaporwave.jpg',
	),
]
