from app.styles.schemas import StyleItem

misc_styles = [
	StyleItem(
		id='misc_architectural',
		name='Misc Architectural',
		origin='Fooocus',
		positive='architectural style {prompt} . clean lines, geometric shapes, minimalist, modern, architectural drawing, highly detailed',
		negative='curved lines, ornate, baroque, abstract, grunge',
		image='styles/misc/architectural.jpg',
	),
	StyleItem(
		id='misc_disco',
		name='Misc Disco',
		origin='Fooocus',
		positive='disco-themed {prompt} . vibrant, groovy, retro 70s style, shiny disco balls, neon lights, dance floor, highly detailed',
		negative='minimalist, rustic, monochrome, contemporary, simplistic',
		image='styles/misc/disco.jpg',
	),
	StyleItem(
		id='misc_dreamscape',
		name='Misc Dreamscape',
		origin='Fooocus',
		positive='dreamscape {prompt} . surreal, ethereal, dreamy, mysterious, fantasy, highly detailed',
		negative='realistic, concrete, ordinary, mundane',
		image='styles/misc/dreamscape.jpg',
	),
	StyleItem(
		id='misc_dystopian',
		name='Misc Dystopian',
		origin='Fooocus',
		positive='dystopian style {prompt} . bleak, post-apocalyptic, somber, dramatic, highly detailed',
		negative='ugly, deformed, noisy, blurry, low contrast, cheerful, optimistic, vibrant, colorful',
		image='styles/misc/dystopian.jpg',
	),
	StyleItem(
		id='misc_fairy-tale',
		name='Misc Fairy Tale',
		origin='Fooocus',
		positive='fairy tale {prompt} . magical, fantastical, enchanting, storybook style, highly detailed',
		negative='realistic, modern, ordinary, mundane',
		image='styles/misc/fairy-tale.jpg',
	),
	StyleItem(
		id='misc_gothic',
		name='Misc Gothic',
		origin='Fooocus',
		positive='gothic style {prompt} . dark, mysterious, haunting, dramatic, ornate, detailed',
		negative='ugly, deformed, noisy, blurry, low contrast, realism, photorealistic, cheerful, optimistic',
		image='styles/misc/gothic.jpg',
	),
	StyleItem(
		id='misc_grunge',
		name='Misc Grunge',
		origin='Fooocus',
		positive='grunge style {prompt} . textured, distressed, vintage, edgy, punk rock vibe, dirty, noisy',
		negative='smooth, clean, minimalist, sleek, modern, photorealistic',
		image='styles/misc/grunge.jpg',
	),
	StyleItem(
		id='misc_horror',
		name='Misc Horror',
		origin='Fooocus',
		positive='horror-themed {prompt} . eerie, unsettling, dark, spooky, suspenseful, grim, highly detailed',
		negative='cheerful, bright, vibrant, light-hearted, cute',
		image='styles/misc/horror.jpg',
	),
	StyleItem(
		id='misc_kawaii',
		name='Misc Kawaii',
		origin='Fooocus',
		positive='kawaii style {prompt} . cute, adorable, brightly colored, cheerful, anime influence, highly detailed',
		negative='dark, scary, realistic, monochrome, abstract',
		image='styles/misc/kawaii.jpg',
	),
	StyleItem(
		id='misc_lovecraftian',
		name='Misc Lovecraftian',
		origin='Fooocus',
		positive='lovecraftian horror {prompt} . eldritch, cosmic horror, unknown, mysterious, surreal, highly detailed',
		negative='light-hearted, mundane, familiar, simplistic, realistic',
		image='styles/misc/lovecraftian.jpg',
	),
	StyleItem(
		id='misc_macabre',
		name='Misc Macabre',
		origin='Fooocus',
		positive='macabre style {prompt} . dark, gothic, grim, haunting, highly detailed',
		negative='bright, cheerful, light-hearted, cartoonish, cute',
		image='styles/misc/macabre.jpg',
	),
	StyleItem(
		id='misc_manga',
		name='Misc Manga',
		origin='Fooocus',
		positive='manga style {prompt} . vibrant, high-energy, detailed, iconic, Japanese comic style',
		negative='ugly, deformed, noisy, blurry, low contrast, realism, photorealistic, Western comic style',
		image='styles/misc/manga.jpg',
	),
	StyleItem(
		id='misc_metropolis',
		name='Misc Metropolis',
		origin='Fooocus',
		positive='metropolis-themed {prompt} . urban, cityscape, skyscrapers, modern, futuristic, highly detailed',
		negative='rural, natural, rustic, historical, simple',
		image='styles/misc/metropolis.jpg',
	),
	StyleItem(
		id='misc_minimalist',
		name='Misc Minimalist',
		origin='Fooocus',
		positive='minimalist style {prompt} . simple, clean, uncluttered, modern, elegant',
		negative='ornate, complicated, highly detailed, cluttered, disordered, messy, noisy',
		image='styles/misc/minimalist.jpg',
	),
	StyleItem(
		id='misc_monochrome',
		name='Misc Monochrome',
		origin='Fooocus',
		positive='monochrome {prompt} . black and white, contrast, tone, texture, detailed',
		negative='colorful, vibrant, noisy, blurry, deformed',
		image='styles/misc/monochrome.jpg',
	),
	StyleItem(
		id='misc_nautical',
		name='Misc Nautical',
		origin='Fooocus',
		positive='nautical-themed {prompt} . sea, ocean, ships, maritime, beach, marine life, highly detailed',
		negative='landlocked, desert, mountains, urban, rustic',
		image='styles/misc/nautical.jpg',
	),
	StyleItem(
		id='misc_space',
		name='Misc Space',
		origin='Fooocus',
		positive='space-themed {prompt} . cosmic, celestial, stars, galaxies, nebulas, planets, science fiction, highly detailed',
		negative='earthly, mundane, ground-based, realism',
		image='styles/misc/space.jpg',
	),
	StyleItem(
		id='misc_stained-glass',
		name='Misc Stained Glass',
		origin='Fooocus',
		positive='stained glass style {prompt} . vibrant, beautiful, translucent, intricate, detailed',
		negative='ugly, deformed, noisy, blurry, low contrast, realism, photorealistic',
		image='styles/misc/stained-glass.jpg',
	),
	StyleItem(
		id='misc_techwear-fashion',
		name='Misc Techwear Fashion',
		origin='Fooocus',
		positive='techwear fashion {prompt} . futuristic, cyberpunk, urban, tactical, sleek, dark, highly detailed',
		negative='vintage, rural, colorful, low contrast, realism, sketch, watercolor',
		image='styles/misc/techwear-fashion.jpg',
	),
	StyleItem(
		id='misc_tribal',
		name='Misc Tribal',
		origin='Fooocus',
		positive='tribal style {prompt} . indigenous, ethnic, traditional patterns, bold, natural colors, highly detailed',
		negative='modern, futuristic, minimalist, pastel',
		image='styles/misc/tribal.jpg',
	),
	StyleItem(
		id='misc_zentangle',
		name='Misc Zentangle',
		origin='Fooocus',
		positive='zentangle {prompt} . intricate, abstract, monochrome, patterns, meditative, highly detailed',
		negative='colorful, representative, simplistic, large fields of color',
		image='styles/misc/zentangle.jpg',
	),
]
