from app.styles.schemas import StyleItem

mk_styles = [
	StyleItem(
		id='mk_chromolithography',
		name='Mk Chromolithography',
		origin='Fooocus',
		positive='Chromolithograph {prompt}. Vibrant colors, intricate details, rich color saturation, meticulous registration, multi-layered printing, decorative elements, historical charm, artistic reproductions, commercial posters, nostalgic, ornate compositions.',
		negative='monochromatic, simple designs, limited color palette, imprecise registration, minimalistic, modern aesthetic, digital appearance.',
		image='styles/mk/chromolithography.jpg',
	),
	StyleItem(
		id='mk_cross-processing-print',
		name='Mk Cross Processing Print',
		origin='Fooocus',
		positive='Cross processing print {prompt}. Experimental color shifts, unconventional tonalities, vibrant and surreal hues, heightened contrasts, unpredictable results, artistic unpredictability, retro and vintage feel, dynamic color interplay, abstract and dreamlike.',
		negative='predictable color tones, traditional processing, realistic color representation, subdued contrasts, standard photographic aesthetics.',
		image='styles/mk/cross-processing-print.jpg',
	),
	StyleItem(
		id='mk_dufaycolor-photograph',
		name='Mk Dufaycolor Photograph',
		origin='Fooocus',
		positive='Dufaycolor photograph {prompt}. Vintage color palette, distinctive color rendering, soft and dreamy atmosphere, historical charm, unique color process, grainy texture, evocative mood, nostalgic aesthetic, hand-tinted appearance, artistic patina.',
		negative='modern color reproduction, hyperrealistic tones, sharp and clear details, digital precision, contemporary aesthetic.',
		image='styles/mk/dufaycolor-photograph.jpg',
	),
	StyleItem(
		id='mk_herbarium',
		name='Mk Herbarium',
		origin='Fooocus',
		positive='Herbarium drawing{prompt}. Botanical accuracy, old botanical book illustration, detailed illustrations, pressed plants, delicate and precise linework, scientific documentation, meticulous presentation, educational purpose, organic compositions, timeless aesthetic, naturalistic beauty.',
		negative='abstract representation, vibrant colors, artistic interpretation, chaotic compositions, fantastical elements, digital appearance.',
		image='styles/mk/herbarium.jpg',
	),
	StyleItem(
		id='mk_punk-collage',
		name='Mk Punk Collage',
		origin='Fooocus',
		positive='punk collage style {prompt} . mixed media, papercut,textured paper, overlapping, ripped posters, safety pins, chaotic layers, graffiti-style elements, anarchy symbols, vintage photos, cut-and-paste aesthetic, bold typography, distorted images, political messages, urban decay, distressed textures, newspaper clippings, spray paint, rebellious icons, DIY spirit, vivid colors, punk band logos, edgy and raw compositions,',
		negative='conventional,blurry, noisy, low contrast',
		image='styles/mk/punk-collage.jpg',
	),
	StyleItem(
		id='mk_mosaic',
		name='Mk Mosaic',
		origin='Fooocus',
		positive='mosaic style {prompt} . fragmented, assembled, colorful, highly detailed',
		negative='whole, unbroken, monochrome',
		image='styles/mk/mosaic.jpg',
	),
	StyleItem(
		id='mk_van-gogh',
		name='Mk Van Gogh',
		origin='Fooocus',
		positive='Oil painting by Van Gogh {prompt} . Expressive, impasto, swirling brushwork, vibrant, brush strokes, Brushstroke-heavy, Textured, Impasto, Colorful, Dynamic, Bold, Distinctive, Vibrant, Whirling, Expressive, Dramatic, Swirling, Layered, Intense, Contrastive, Atmospheric, Luminous, Textural, Evocative, SpiraledVan Gogh style',
		negative='realistic, photorealistic, calm, straight lines, signature, frame, text, watermark',
		image='styles/mk/van-gogh.jpg',
	),
	StyleItem(
		id='mk_coloring-book',
		name='Mk Coloring Book',
		origin='Fooocus',
		positive='centered black and white high contrast line drawing, coloring book style,{prompt} . monochrome, blank white background',
		negative='greyscale, gradients,shadows,shadow, colored, Red, Blue, Yellow, Green, Orange, Purple, Pink, Brown, Gray, Beige, Turquoise, Lavender, Cyan, Magenta, Olive, Indigo, black background',
		image='styles/mk/coloring-book.jpg',
	),
	StyleItem(
		id='mk_singer-sargent',
		name='Mk Singer Sargent',
		origin='Fooocus',
		positive='Oil painting by John Singer Sargent {prompt}. Elegant, refined, masterful technique,realistic portrayal, subtle play of light, captivating expression, rich details, harmonious colors, skillful composition, brush strokes, chiaroscuro.',
		negative='realistic, photorealistic, abstract, overly stylized, excessive contrasts, distorted,bright colors,disorder.',
		image='styles/mk/singer-sargent.jpg',
	),
	StyleItem(
		id='mk_pollock',
		name='Mk Pollock',
		origin='Fooocus',
		positive='Oil painting by Jackson Pollock {prompt}. Abstract expressionism, drip painting, chaotic composition, energetic, spontaneous, unconventional technique, dynamic, bold, distinctive, vibrant, intense, expressive, energetic, layered, non-representational, gestural.',
		negative='(realistic:1.5), (photorealistic:1.5), representational, calm, ordered composition, precise lines, detailed forms, subdued colors, quiet, static, traditional, figurative.',
		image='styles/mk/pollock.jpg',
	),
	StyleItem(
		id='mk_basquiat',
		name='Mk Basquiat',
		origin='Fooocus',
		positive='Artwork by Jean-Michel Basquiat {prompt}. Neo-expressionism, street art influence, graffiti-inspired, raw, energetic, bold colors, dynamic composition, chaotic, layered, textural, expressive, spontaneous, distinctive, symbolic,energetic brushstrokes.',
		negative='(realistic:1.5), (photorealistic:1.5), calm, precise lines, conventional composition, subdued',
		image='styles/mk/basquiat.jpg',
	),
	StyleItem(
		id='mk_andy-warhol',
		name='Mk Andy Warhol',
		origin='Fooocus',
		positive='Artwork in the style of Andy Warhol {prompt}. Pop art, vibrant colors, bold compositions, repetition of iconic imagery, celebrity culture, commercial aesthetics, mass production influence, stylized simplicity, cultural commentary, graphical elements, distinctive portraits.',
		negative='subdued colors, realistic, lack of repetition, minimalistic.',
		image='styles/mk/andy-warhol.jpg',
	),
	StyleItem(
		id='mk_halftone-print',
		name='Mk Halftone Print',
		origin='Fooocus',
		positive='Halftone print of {prompt}. Dot matrix pattern, grayscale tones, vintage aesthetic, newspaper print vibe, stylized dots, visual texture, black and white contrasts, retro appearance, artistic pointillism,pop culture, (Roy Lichtenstein style:1.5).',
		negative='smooth gradients, continuous tones, vibrant colors.',
		image='styles/mk/halftone-print.jpg',
	),
	StyleItem(
		id='mk_gond-painting',
		name='Mk Gond Painting',
		origin='Fooocus',
		positive='Gond painting {prompt}. Intricate patterns, vibrant colors, detailed motifs, nature-inspired themes, tribal folklore, fine lines, intricate detailing, storytelling compositions, mystical and folkloric, cultural richness.',
		negative='monochromatic, abstract shapes, minimalistic.',
		image='styles/mk/gond-painting.jpg',
	),
	StyleItem(
		id='mk_albumen-print',
		name='Mk Albumen Print',
		origin='Fooocus',
		positive='Albumen print {prompt}. Sepia tones, fine details, subtle tonal gradations, delicate highlights, vintage aesthetic, soft and muted atmosphere, historical charm, rich textures, meticulous craftsmanship, classic photographic technique, vignetting.',
		negative='vibrant colors, high contrast, modern, digital appearance, sharp details, contemporary style.',
		image='styles/mk/albumen-print.jpg',
	),
	StyleItem(
		id='mk_aquatint-print',
		name='Mk Aquatint Print',
		origin='Fooocus',
		positive='Aquatint print {prompt}. Soft tonal gradations, atmospheric effects, velvety textures, rich contrasts, fine details, etching process, delicate lines, nuanced shading, expressive and moody atmosphere, artistic depth.',
		negative='sharp contrasts, bold lines, minimalistic.',
		image='styles/mk/aquatint-print.jpg',
	),
	StyleItem(
		id='mk_anthotype-print',
		name='Mk Anthotype Print',
		origin='Fooocus',
		positive='Anthotype print {prompt}. Monochrome dye, soft and muted colors, organic textures, ephemeral and delicate appearance, low details, watercolor canvas, low contrast, overexposed, silhouette, textured paper.',
		negative='vibrant synthetic dyes, bold and saturated colors.',
		image='styles/mk/anthotype-print.jpg',
	),
	StyleItem(
		id='mk_inuit-carving',
		name='Mk Inuit Carving',
		origin='Fooocus',
		positive='A sculpture made of ivory, {prompt} made of . Sculptures, Inuit art style, intricate carvings, natural materials, storytelling motifs, arctic wildlife themes, symbolic representations, cultural traditions, earthy tones, harmonious compositions, spiritual and mythological elements.',
		negative='abstract, vibrant colors.',
		image='styles/mk/inuit-carving.jpg',
	),
	StyleItem(
		id='mk_bromoil-print',
		name='Mk Bromoil Print',
		origin='Fooocus',
		positive='Bromoil print {prompt}. Painterly effects, sepia tones, textured surfaces, rich contrasts, expressive brushwork, tonal variations, vintage aesthetic, atmospheric mood, handmade quality, artistic experimentation, darkroom craftsmanship, vignetting.',
		negative='smooth surfaces, minimal brushwork, contemporary digital appearance.',
		image='styles/mk/bromoil-print.jpg',
	),
	StyleItem(
		id='mk_calotype-print',
		name='Mk Calotype Print',
		origin='Fooocus',
		positive='Calotype print {prompt}. Soft focus, subtle tonal range, paper negative process, fine details, vintage aesthetic, artistic experimentation, atmospheric mood, early photographic charm, handmade quality, vignetting.',
		negative='sharp focus, bold contrasts, modern aesthetic, digital photography.',
		image='styles/mk/calotype-print.jpg',
	),
	StyleItem(
		id='mk_color-sketchnote',
		name='Mk Color Sketchnote',
		origin='Fooocus',
		positive='Color sketchnote {prompt}. Hand-drawn elements, vibrant colors, visual hierarchy, playful illustrations, varied typography, graphic icons, organic and dynamic layout, personalized touches, creative expression, engaging storytelling.',
		negative='monochromatic, geometric layout.',
		image='styles/mk/color-sketchnote.jpg',
	),
	StyleItem(
		id='mk_cibulak-porcelain',
		name='Mk Cibulak Porcelain',
		origin='Fooocus',
		positive='A sculpture made of blue pattern porcelain of {prompt}. Classic design, blue and white color scheme, intricate detailing, floral motifs, onion-shaped elements, historical charm, rococo, white ware, cobalt blue, underglaze pattern, fine craftsmanship, traditional elegance, delicate patterns, vintage aesthetic, Meissen, Blue Onion pattern, Cibulak.',
		negative='tea, teapot, cup, teacup,bright colors, bold and modern design, absence of intricate detailing, lack of floral motifs, non-traditional shapes.',
		image='styles/mk/cibulak-porcelain.jpg',
	),
	StyleItem(
		id='mk_alcohol-ink-art',
		name='Mk Alcohol Ink Art',
		origin='Fooocus',
		positive='Alcohol ink art {prompt}. Fluid and vibrant colors, unpredictable patterns, organic textures, translucent layers, abstract compositions, ethereal and dreamy effects, free-flowing movement, expressive brushstrokes, contemporary aesthetic, wet textured paper.',
		negative='monochromatic, controlled patterns.',
		image='styles/mk/alcohol-ink-art.jpg',
	),
	StyleItem(
		id='mk_one-line-art',
		name='Mk One Line Art',
		origin='Fooocus',
		positive='One line art {prompt}. Continuous and unbroken black line, minimalistic, simplicity, economical use of space, flowing and dynamic, symbolic representations, contemporary aesthetic, evocative and abstract, white background.',
		negative='disjointed lines, complexity, complex detailing.',
		image='styles/mk/one-line-art.jpg',
	),
	StyleItem(
		id='mk_blacklight-paint',
		name='Mk Blacklight Paint',
		origin='Fooocus',
		positive='Blacklight paint {prompt}. Fluorescent pigments, vibrant and surreal colors, ethereal glow, otherworldly effects, dynamic and psychedelic compositions, neon aesthetics, transformative in ultraviolet light, contemporary and experimental.',
		negative='muted colors, traditional and realistic compositions.',
		image='styles/mk/blacklight-paint.jpg',
	),
	StyleItem(
		id='mk_carnival-glass',
		name='Mk Carnival Glass',
		origin='Fooocus',
		positive='A sculpture made of Carnival glass, {prompt}. Iridescent surfaces, vibrant colors, intricate patterns, opalescent hues, reflective and prismatic effects, Art Nouveau and Art Deco influences, vintage charm, intricate detailing, lustrous and luminous appearance, Carnival Glass style.',
		negative='non-iridescent surfaces, muted colors, absence of intricate patterns, lack of opalescent hues, modern and minimalist aesthetic.',
		image='styles/mk/carnival-glass.jpg',
	),
	StyleItem(
		id='mk_cyanotype-print',
		name='Mk Cyanotype Print',
		origin='Fooocus',
		positive='Cyanotype print {prompt}. Prussian blue tones, distinctive coloration, high contrast, blueprint aesthetics, atmospheric mood, sun-exposed paper, silhouette effects, delicate details, historical charm, handmade and experimental quality.',
		negative='vibrant colors, low contrast, modern and polished appearance.',
		image='styles/mk/cyanotype-print.jpg',
	),
	StyleItem(
		id='mk_cross-stitching',
		name='Mk Cross Stitching',
		origin='Fooocus',
		positive='Cross-stitching {prompt}. Intricate patterns, embroidery thread, sewing, fine details, precise stitches, textile artistry, symmetrical designs, varied color palette, traditional and contemporary motifs, handmade and crafted,canvas, nostalgic charm.',
		negative='paper, paint, ink, photography.',
		image='styles/mk/cross-stitching.jpg',
	),
	StyleItem(
		id='mk_encaustic-paint',
		name='Mk Encaustic Paint',
		origin='Fooocus',
		positive='Encaustic paint {prompt}. Textured surfaces, translucent layers, luminous quality, wax medium, rich color saturation, fluid and organic shapes, contemporary and historical influences, mixed media elements, atmospheric depth.',
		negative='flat surfaces, opaque layers, lack of wax medium, muted color palette, absence of textured surfaces, non-mixed media.',
		image='styles/mk/encaustic-paint.jpg',
	),
	StyleItem(
		id='mk_embroidery',
		name='Mk Embroidery',
		origin='Fooocus',
		positive='Embroidery {prompt}. Intricate stitching, embroidery thread, fine details, varied thread textures, textile artistry, embellished surfaces, diverse color palette, traditional and contemporary motifs, handmade and crafted, tactile and ornate.',
		negative='minimalist, monochromatic.',
		image='styles/mk/embroidery.jpg',
	),
	StyleItem(
		id='mk_gyotaku',
		name='Mk Gyotaku',
		origin='Fooocus',
		positive='Gyotaku {prompt}. Fish impressions, realistic details, ink rubbings, textured surfaces, traditional Japanese art form, nature-inspired compositions, artistic representation of marine life, black and white contrasts, cultural significance.',
		negative='photography.',
		image='styles/mk/gyotaku.jpg',
	),
	StyleItem(
		id='mk_luminogram',
		name='Mk Luminogram',
		origin='Fooocus',
		positive='Luminogram {prompt}. Photogram technique, ethereal and abstract effects, light and shadow interplay, luminous quality, experimental process, direct light exposure, unique and unpredictable results, artistic experimentation.',
		image='styles/mk/luminogram.jpg',
	),
	StyleItem(
		id='mk_lite-brite-art',
		name='Mk Lite Brite Art',
		origin='Fooocus',
		positive='Lite Brite art {prompt}. Luminous and colorful designs, pixelated compositions, retro aesthetic, glowing effects, creative patterns, interactive and playful, nostalgic charm, vibrant and dynamic arrangements.',
		negative='monochromatic.',
		image='styles/mk/lite-brite-art.jpg',
	),
	StyleItem(
		id='mk_mokume-gane',
		name='Mk Mokume Gane',
		origin='Fooocus',
		positive='Mokume-gane {prompt}. Wood-grain patterns, mixed metal layers, intricate and organic designs, traditional Japanese metalwork, harmonious color combinations, artisanal craftsmanship, unique and layered textures, cultural and historical significance.',
		negative='uniform metal surfaces.',
		image='styles/mk/mokume-gane.jpg',
	),
	StyleItem(
		id='mk_palekh',
		name='Mk Palekh',
		origin='Fooocus',
		positive='Palekh art {prompt}. Miniature paintings, intricate details, vivid colors, folkloric themes, lacquer finish, storytelling compositions, symbolic elements, Russian folklore influence, cultural and historical significance.',
		negative='large-scale paintings.',
		image='styles/mk/palekh.jpg',
	),
	StyleItem(
		id='mk_suminagashi',
		name='Mk Suminagashi',
		origin='Fooocus',
		positive='Suminagashi {prompt}. Floating ink patterns, marbled effects, delicate and ethereal designs, water-based ink, fluid and unpredictable compositions, meditative process, monochromatic or subtle color palette, Japanese artistic tradition.',
		negative='vibrant and bold color palette.',
		image='styles/mk/suminagashi.jpg',
	),
	StyleItem(
		id='mk_scrimshaw',
		name='Mk Scrimshaw',
		origin='Fooocus',
		positive="A Scrimshaw engraving of {prompt}. Intricate engravings on a spermwhale's teeth, marine motifs, detailed scenes, nautical themes, black and white contrasts, historical craftsmanship, artisanal carving, storytelling compositions, maritime heritage.",
		negative='colorful, modern.',
		image='styles/mk/scrimshaw.jpg',
	),
	StyleItem(
		id='mk_shibori',
		name='Mk Shibori',
		origin='Fooocus',
		positive='Shibori {prompt}. Textured fabric, intricate patterns, resist-dyeing technique, indigo or vibrant colors, organic and flowing designs, Japanese textile art, cultural tradition, tactile and visual interest.',
		negative='monochromatic.',
		image='styles/mk/shibori.jpg',
	),
	StyleItem(
		id='mk_vitreous-enamel',
		name='Mk Vitreous Enamel',
		origin='Fooocus',
		positive='A sculpture made of Vitreous enamel {prompt}. Smooth and glossy surfaces, vibrant colors, glass-like finish, durable and resilient, intricate detailing, traditional and contemporary applications, artistic craftsmanship, jewelry and decorative objects, , Vitreous enamel, colored glass.',
		negative='rough surfaces, muted colors.',
		image='styles/mk/vitreous-enamel.jpg',
	),
	StyleItem(
		id='mk_ukiyo-e',
		name='Mk Ukiyo E',
		origin='Fooocus',
		positive='Ukiyo-e {prompt}. Woodblock prints, vibrant colors, intricate details, depictions of landscapes, kabuki actors, beautiful women, cultural scenes, traditional Japanese art, artistic craftsmanship, historical significance.',
		negative='absence of woodblock prints, muted colors, lack of intricate details, non-traditional Japanese themes, absence of cultural scenes.',
		image='styles/mk/ukiyo-e.jpg',
	),
	StyleItem(
		id='mk_vintage-airline-poster',
		name='Mk Vintage Airline Poster',
		origin='Fooocus',
		positive='vintage airline poster {prompt} . classic aviation fonts, pastel colors, elegant aircraft illustrations, scenic destinations, distressed textures, retro travel allure',
		negative='modern fonts, bold colors, hyper-realistic, sleek design',
		image='styles/mk/vintage-airline-poster.jpg',
	),
	StyleItem(
		id='mk_vintage-travel-poster',
		name='Mk Vintage Travel Poster',
		origin='Fooocus',
		positive='vintage travel poster {prompt} . retro fonts, muted colors, scenic illustrations, iconic landmarks, distressed textures, nostalgic vibes',
		negative='modern fonts, vibrant colors, hyper-realistic, sleek design',
		image='styles/mk/vintage-travel-poster.jpg',
	),
	StyleItem(
		id='mk_bauhaus-style',
		name='Mk Bauhaus Style',
		origin='Fooocus',
		positive='Bauhaus-inspired {prompt} . minimalism, geometric precision, primary colors, sans-serif typography, asymmetry, functional design',
		negative='ornate, intricate, excessive detail, complex patterns, serif typography',
		image='styles/mk/bauhaus-style.jpg',
	),
	StyleItem(
		id='mk_afrofuturism',
		name='Mk Afrofuturism',
		origin='Fooocus',
		positive='Afrofuturism illustration {prompt} . vibrant colors, futuristic elements, cultural symbolism, cosmic imagery, dynamic patterns, empowering narratives',
		negative='monochromatic',
		image='styles/mk/afrofuturism.jpg',
	),
	StyleItem(
		id='mk_atompunk',
		name='Mk Atompunk',
		origin='Fooocus',
		positive='Atompunk illustation, {prompt} . retro-futuristic, atomic age aesthetics, sleek lines, metallic textures, futuristic technology, optimism, energy',
		negative='organic, natural textures, rustic, dystopian',
		image='styles/mk/atompunk.jpg',
	),
	StyleItem(
		id='mk_constructivism',
		name='Mk Constructivism',
		origin='Fooocus',
		positive='Constructivism {prompt} . geometric abstraction, bold colors, industrial aesthetics, dynamic compositions, utilitarian design, revolutionary spirit',
		negative='organic shapes, muted colors, ornate elements, traditional',
		image='styles/mk/constructivism.jpg',
	),
	StyleItem(
		id='mk_chicano-art',
		name='Mk Chicano Art',
		origin='Fooocus',
		positive='Chicano art {prompt} . bold colors, cultural symbolism, muralism, lowrider aesthetics, barrio life, political messages, social activism, Mexico',
		negative='monochromatic, minimalist, mainstream aesthetics',
		image='styles/mk/chicano-art.jpg',
	),
	StyleItem(
		id='mk_de-stijl',
		name='Mk De Stijl',
		origin='Fooocus',
		positive='De Stijl Art {prompt} . neoplasticism, primary colors, geometric abstraction, horizontal and vertical lines, simplicity, harmony, utopian ideals',
		negative='complex patterns, muted colors, ornate elements, asymmetry',
		image='styles/mk/de-stijl.jpg',
	),
	StyleItem(
		id='mk_dayak-art',
		name='Mk Dayak Art',
		origin='Fooocus',
		positive='Dayak art sculpture of {prompt} . intricate patterns, nature-inspired motifs, vibrant colors, traditional craftsmanship, cultural symbolism, storytelling',
		negative='minimalist, monochromatic, modern',
		image='styles/mk/dayak-art.jpg',
	),
	StyleItem(
		id='mk_fayum-portrait',
		name='Mk Fayum Portrait',
		origin='Fooocus',
		positive='Fayum portrait {prompt} . encaustic painting, realistic facial features, warm earth tones, serene expressions, ancient Egyptian influences',
		negative='abstract, vibrant colors, exaggerated features, modern',
		image='styles/mk/fayum-portrait.jpg',
	),
	StyleItem(
		id='mk_illuminated-manuscript',
		name='Mk Illuminated Manuscript',
		origin='Fooocus',
		positive='Illuminated manuscript {prompt} . intricate calligraphy, rich colors, detailed illustrations, gold leaf accents, ornate borders, religious, historical, medieval',
		negative='modern typography, minimalist design, monochromatic, abstract themes',
		image='styles/mk/illuminated-manuscript.jpg',
	),
	StyleItem(
		id='mk_kalighat-painting',
		name='Mk Kalighat Painting',
		origin='Fooocus',
		positive='Kalighat painting {prompt} . bold lines, vibrant colors, narrative storytelling, cultural motifs, flat compositions, expressive characters',
		negative='subdued colors, intricate details, realistic portrayal, modern aesthetics',
		image='styles/mk/kalighat-painting.jpg',
	),
	StyleItem(
		id='mk_madhubani-painting',
		name='Mk Madhubani Painting',
		origin='Fooocus',
		positive='Madhubani painting {prompt} . intricate patterns, vibrant colors, nature-inspired motifs, cultural storytelling, symmetry, folk art aesthetics',
		negative='abstract, muted colors, minimalistic design, modern aesthetics',
		image='styles/mk/madhubani-painting.jpg',
	),
	StyleItem(
		id='mk_pictorialism',
		name='Mk Pictorialism',
		origin='Fooocus',
		positive='Pictorialism illustration{prompt} . soft focus, atmospheric effects, artistic interpretation, tonality, muted colors, evocative storytelling',
		negative='sharp focus, high contrast, realistic depiction, vivid colors',
		image='styles/mk/pictorialism.jpg',
	),
	StyleItem(
		id='mk_pichwai-painting',
		name='Mk Pichwai Painting',
		origin='Fooocus',
		positive='Pichwai painting {prompt} . intricate detailing, vibrant colors, religious themes, nature motifs, devotional storytelling, gold leaf accents',
		negative='minimalist, subdued colors, abstract design',
		image='styles/mk/pichwai-painting.jpg',
	),
	StyleItem(
		id='mk_patachitra-painting',
		name='Mk Patachitra Painting',
		origin='Fooocus',
		positive='Patachitra painting {prompt} . bold outlines, vibrant colors, intricate detailing, mythological themes, storytelling, traditional craftsmanship',
		negative='subdued colors, minimalistic, abstract, modern aesthetics',
		image='styles/mk/patachitra-painting.jpg',
	),
	StyleItem(
		id='mk_samoan-art-inspired',
		name='Mk Samoan Art Inspired',
		origin='Fooocus',
		positive='Samoan art-inspired wooden sculpture {prompt} . traditional motifs, natural elements, bold colors, cultural symbolism, storytelling, craftsmanship',
		negative='modern aesthetics, minimalist, abstract',
		image='styles/mk/samoan-art-inspired.jpg',
	),
	StyleItem(
		id='mk_tlingit-art',
		name='Mk Tlingit Art',
		origin='Fooocus',
		positive='Tlingit art {prompt} . formline design, natural elements, animal motifs, bold colors, cultural storytelling, traditional craftsmanship, Alaska traditional art, (totem:1.5)',
		image='styles/mk/tlingit-art.jpg',
	),
	StyleItem(
		id='mk_adnate-style',
		name='Mk Adnate Style',
		origin='Fooocus',
		positive='Painting by Adnate {prompt} . realistic portraits, street art, large-scale murals, subdued color palette, social narratives',
		negative='abstract, vibrant colors, small-scale art',
		image='styles/mk/adnate-style.jpg',
	),
	StyleItem(
		id='mk_ron-english-style',
		name='Mk Ron English Style',
		origin='Fooocus',
		positive='Painting by Ron English {prompt} . pop-surrealism, cultural subversion, iconic mash-ups, vibrant and bold colors, satirical commentary',
		negative='traditional, monochromatic',
		image='styles/mk/ron-english-style.jpg',
	),
	StyleItem(
		id='mk_shepard-fairey-style',
		name='Mk Shepard Fairey Style',
		origin='Fooocus',
		positive='Painting by Shepard Fairey {prompt} . street art, political activism, iconic stencils, bold typography, high contrast, red, black, and white color palette',
		negative='traditional, muted colors',
		image='styles/mk/shepard-fairey-style.jpg',
	),
]
