from app.styles.schemas import StyleItem

papercraft_styles = [
	StyleItem(
		id='papercraft_collage',
		name='Papercraft Collage',
		origin='Fooocus',
		positive='collage style {prompt} . mixed media, layered, textural, detailed, artistic',
		negative='ugly, deformed, noisy, blurry, low contrast, realism, photorealistic',
		image='styles/papercraft/collage.jpg',
	),
	StyleItem(
		id='papercraft_flat-papercut',
		name='Papercraft Flat Papercut',
		origin='Fooocus',
		positive='flat papercut style {prompt} . silhouette, clean cuts, paper, sharp edges, minimalist, color block',
		negative='3D, high detail, noise, grainy, blurry, painting, drawing, photo, disfigured',
		image='styles/papercraft/flat-papercut.jpg',
	),
	StyleItem(
		id='papercraft_kirigami',
		name='Papercraft Kirigami',
		origin='Fooocus',
		positive='kirigami representation of {prompt} . 3D, paper folding, paper cutting, Japanese, intricate, symmetrical, precision, clean lines',
		negative='painting, drawing, 2D, noisy, blurry, deformed',
		image='styles/papercraft/kirigami.jpg',
	),
	StyleItem(
		id='papercraft_paper-mache',
		name='Papercraft Paper Mache',
		origin='Fooocus',
		positive='paper mache representation of {prompt} . 3D, sculptural, textured, handmade, vibrant, fun',
		negative='2D, flat, photo, sketch, digital art, deformed, noisy, blurry',
		image='styles/papercraft/paper-mache.jpg',
	),
	StyleItem(
		id='papercraft_paper-quilling',
		name='Papercraft Paper Quilling',
		origin='Fooocus',
		positive='paper quilling art of {prompt} . intricate, delicate, curling, rolling, shaping, coiling, loops, 3D, dimensional, ornamental',
		negative='photo, painting, drawing, 2D, flat, deformed, noisy, blurry',
		image='styles/papercraft/paper-quilling.jpg',
	),
	StyleItem(
		id='papercraft_papercut-collage',
		name='Papercraft Papercut Collage',
		origin='Fooocus',
		positive='papercut collage of {prompt} . mixed media, textured paper, overlapping, asymmetrical, abstract, vibrant',
		negative='photo, 3D, realistic, drawing, painting, high detail, disfigured',
		image='styles/papercraft/papercut-collage.jpg',
	),
	StyleItem(
		id='papercraft_papercut-shadow-box',
		name='Papercraft Papercut Shadow Box',
		origin='Fooocus',
		positive='3D papercut shadow box of {prompt} . layered, dimensional, depth, silhouette, shadow, papercut, handmade, high contrast',
		negative='painting, drawing, photo, 2D, flat, high detail, blurry, noisy, disfigured',
		image='styles/papercraft/papercut-shadow-box.jpg',
	),
	StyleItem(
		id='papercraft_stacked-papercut',
		name='Papercraft Stacked Papercut',
		origin='Fooocus',
		positive='stacked papercut art of {prompt} . 3D, layered, dimensional, depth, precision cut, stacked layers, papercut, high contrast',
		negative='2D, flat, noisy, blurry, painting, drawing, photo, deformed',
		image='styles/papercraft/stacked-papercut.jpg',
	),
	StyleItem(
		id='papercraft_thick-layered-papercut',
		name='Papercraft Thick Layered Papercut',
		origin='Fooocus',
		positive='thick layered papercut art of {prompt} . deep 3D, volumetric, dimensional, depth, thick paper, high stack, heavy texture, tangible layers',
		negative='2D, flat, thin paper, low stack, smooth texture, painting, drawing, photo, deformed',
		image='styles/papercraft/thick-layered-papercut.jpg',
	),
]
