from app.styles.schemas import StyleItem

photo_styles = [
	StyleItem(
		id='photo_alien',
		name='Photo Alien',
		origin='Fooocus',
		positive='alien-themed {prompt} . extraterrestrial, cosmic, otherworldly, mysterious, sci-fi, highly detailed',
		negative='earthly, mundane, common, realistic, simple',
		image='styles/photo/alien.jpg',
	),
	StyleItem(
		id='photo_film-noir',
		name='Photo Film Noir',
		origin='Fooocus',
		positive='film noir style {prompt} . monochrome, high contrast, dramatic shadows, 1940s style, mysterious, cinematic',
		negative='ugly, deformed, noisy, blurry, low contrast, realism, photorealistic, vibrant, colorful',
		image='styles/photo/film-noir.jpg',
	),
	StyleItem(
		id='photo_glamour',
		name='Photo Glamour',
		origin='Fooocus',
		positive='glamorous photo {prompt} . high fashion, luxurious, extravagant, stylish, sensual, opulent, elegance, stunning beauty, professional, high contrast, detailed',
		negative='ugly, deformed, noisy, blurry, distorted, grainy, sketch, low contrast, dull, plain, modest',
		image='styles/photo/glamour.jpg',
	),
	StyleItem(
		id='photo_hdr',
		name='Photo Hdr',
		origin='Fooocus',
		positive='HDR photo of {prompt} . High dynamic range, vivid, rich details, clear shadows and highlights, realistic, intense, enhanced contrast, highly detailed',
		negative='flat, low contrast, oversaturated, underexposed, overexposed, blurred, noisy',
		image='styles/photo/hdr.jpg',
	),
	StyleItem(
		id='photo_iphone-photographic',
		name='Photo Iphone Photographic',
		origin='Fooocus',
		positive='iphone photo {prompt} . large depth of field, deep depth of field, highly detailed',
		negative='drawing, painting, crayon, sketch, graphite, impressionist, noisy, blurry, soft, deformed, ugly, shallow depth of field, bokeh',
		image='styles/photo/iphone-photographic.jpg',
	),
	StyleItem(
		id='photo_long-exposure',
		name='Photo Long Exposure',
		origin='Fooocus',
		positive='long exposure photo of {prompt} . Blurred motion, streaks of light, surreal, dreamy, ghosting effect, highly detailed',
		negative='static, noisy, deformed, shaky, abrupt, flat, low contrast',
		image='styles/photo/long-exposure.jpg',
	),
	StyleItem(
		id='photo_neon-noir',
		name='Photo Neon Noir',
		origin='Fooocus',
		positive='neon noir {prompt} . cyberpunk, dark, rainy streets, neon signs, high contrast, low light, vibrant, highly detailed',
		negative='bright, sunny, daytime, low contrast, black and white, sketch, watercolor',
		image='styles/photo/neon-noir.jpg',
	),
	StyleItem(
		id='photo_silhouette',
		name='Photo Silhouette',
		origin='Fooocus',
		positive='silhouette style {prompt} . high contrast, minimalistic, black and white, stark, dramatic',
		negative='ugly, deformed, noisy, blurry, low contrast, color, realism, photorealistic',
		image='styles/photo/silhouette.jpg',
	),
	StyleItem(
		id='photo_tilt-shift',
		name='Photo Tilt Shift',
		origin='Fooocus',
		positive='tilt-shift photo of {prompt} . selective focus, miniature effect, blurred background, highly detailed, vibrant, perspective control',
		negative='blurry, noisy, deformed, flat, low contrast, unrealistic, oversaturated, underexposed',
		image='styles/photo/tilt-shift.jpg',
	),
]
