"""Type stubs for diffusers library.

This module provides type hints for the diffusers library APIs used in this project.
"""

from typing import Any

class AutoPipelineForText2Image:
	"""Auto pipeline for text-to-image generation."""

	def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class AutoPipelineForImage2Image:
	"""Auto pipeline for image-to-image generation."""

	def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

	@classmethod
	def from_pipe(cls, pipe: AutoPipelineForText2Image, **kwargs: Any) -> AutoPipelineForImage2Image: ...

# Scheduler classes
class DDIMScheduler: ...
class DDPMScheduler: ...
class DEISMultistepScheduler: ...
class DPMSolverMultistepScheduler: ...
class DPMSolverSDEScheduler: ...
class DPMSolverSinglestepScheduler: ...
class EulerAncestralDiscreteScheduler: ...
class EulerDiscreteScheduler: ...
class HeunDiscreteScheduler: ...
class KDPM2AncestralDiscreteScheduler: ...
class KDPM2DiscreteScheduler: ...
class LCMScheduler: ...
class LMSDiscreteScheduler: ...
class PNDMScheduler: ...
class TCDScheduler: ...
class UniPCMultistepScheduler: ...
