version: 1
disable_existing_loggers: False

formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  file:
    class: logging.FileHandler
    filename: logs.txt
    mode: w
    formatter: default

  console:
    class: logging.StreamHandler
    formatter: default

loggers:
  watchfiles:
    level: WARNING
    handlers: [file, console]
    propagate: False

  uvicorn:
    level: INFO
    handlers: [file, console]
    propagate: False

  uvicorn.error:
    level: INFO
    handlers: [file, console]
    propagate: False

  uvicorn.access:
    level: INFO
    handlers: [file, console]
    propagate: False

root:
  level: INFO
  handlers: [file, console]
