"""add safety_check_enabled to config

Revision ID: 210795559cec
Revises: d7badfc4c206
Create Date: 2025-12-03 10:45:42.835648

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '210795559cec'
down_revision: Union[str, Sequence[str], None] = 'd7badfc4c206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('config', sa.Column('safety_check_enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False))
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column('config', 'safety_check_enabled')
	# ### end Alembic commands ###
