"""Added is_nsfw to generated images table

Revision ID: 2468ba64f2ee
Revises: aeb6848de74b
Create Date: 2025-07-28 10:24:08.798422

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2468ba64f2ee'
down_revision: Union[str, Sequence[str], None] = 'aeb6848de74b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('generated_images', sa.Column('is_nsfw', sa.Boolean(), server_default=sa.text('0'), nullable=False))
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column('generated_images', 'is_nsfw')
	# ### end Alembic commands ###
