"""Renamed ram and gpu with scale factor

Revision ID: 8fff7131769e
Revises: 2468ba64f2ee
Create Date: 2025-07-30 08:07:51.026793

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8fff7131769e'
down_revision: Union[str, Sequence[str], None] = '2468ba64f2ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('config', sa.Column('ram_scale_factor', sa.Float(), nullable=False))
	op.add_column('config', sa.Column('gpu_scale_factor', sa.Float(), nullable=False))
	op.drop_column('config', 'ram')
	op.drop_column('config', 'gpu')
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('config', sa.Column('gpu', sa.FLOAT(), nullable=False))
	op.add_column('config', sa.Column('ram', sa.FLOAT(), nullable=False))
	op.drop_column('config', 'gpu_scale_factor')
	op.drop_column('config', 'ram_scale_factor')
	# ### end Alembic commands ###
