"""Added file name to generated images

Revision ID: aeb6848de74b
Revises: f475e8680ade
Create Date: 2025-07-27 23:46:20.496178

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aeb6848de74b'
down_revision: Union[str, Sequence[str], None] = 'f475e8680ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('generated_images', sa.Column('file_name', sa.String(), nullable=False))
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column('generated_images', 'file_name')
	# ### end Alembic commands ###
