"""add loras table

Revision ID: d7badfc4c206
Revises: 8fff7131769e
Create Date: 2025-11-18 09:48:22.877045

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd7badfc4c206'
down_revision: Union[str, Sequence[str], None] = '8fff7131769e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'loras',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('name', sa.String(), nullable=False),
		sa.Column('file_path', sa.String(), nullable=False),
		sa.Column('file_size', sa.Integer(), nullable=False),
		sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
		sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
		sa.PrimaryKeyConstraint('id'),
		sa.UniqueConstraint('file_path'),
	)
	op.create_index(op.f('ix_loras_id'), 'loras', ['id'], unique=False)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f('ix_loras_id'), table_name='loras')
	op.drop_table('loras')
	# ### end Alembic commands ###
