"""Init schema

Revision ID: f475e8680ade
Revises:
Create Date: 2025-07-20 11:38:13.116251

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f475e8680ade'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'config',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('device_index', sa.Integer(), nullable=False),
		sa.Column('ram', sa.Float(), nullable=False),
		sa.Column('gpu', sa.Float(), nullable=False),
		sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
		sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
		sa.PrimaryKeyConstraint('id'),
	)
	op.create_index(op.f('ix_config_id'), 'config', ['id'], unique=False)
	op.create_table(
		'histories',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('prompt', sa.String(), nullable=False),
		sa.Column('model', sa.String(), nullable=False),
		sa.Column('config', sa.JSON(), nullable=False),
		sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
		sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
		sa.PrimaryKeyConstraint('id'),
	)
	op.create_index(op.f('ix_histories_id'), 'histories', ['id'], unique=False)
	op.create_table(
		'models',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('model_id', sa.String(), nullable=False),
		sa.Column('model_dir', sa.String(), nullable=False),
		sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
		sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
		sa.PrimaryKeyConstraint('id'),
		sa.UniqueConstraint('model_dir'),
		sa.UniqueConstraint('model_id'),
	)
	op.create_index(op.f('ix_models_id'), 'models', ['id'], unique=False)
	op.create_table(
		'generated_images',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('history_id', sa.Integer(), nullable=False),
		sa.Column('path', sa.String(), nullable=False),
		sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
		sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
		sa.ForeignKeyConstraint(
			['history_id'],
			['histories.id'],
		),
		sa.PrimaryKeyConstraint('id'),
	)
	op.create_index(op.f('ix_generated_images_id'), 'generated_images', ['id'], unique=False)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f('ix_generated_images_id'), table_name='generated_images')
	op.drop_table('generated_images')
	op.drop_index(op.f('ix_models_id'), table_name='models')
	op.drop_table('models')
	op.drop_index(op.f('ix_histories_id'), table_name='histories')
	op.drop_table('histories')
	op.drop_index(op.f('ix_config_id'), table_name='config')
	op.drop_table('config')
	# ### end Alembic commands ###
