from app.schemas.styles import StyleItem

game_styles = [
	StyleItem(
		id='game_bubble-bobble',
		name='Game Bubble Bobble',
		origin='Fooocus',
		positive='Bubble Bobble style {prompt} . 8-bit, cute, pixelated, fantasy, vibrant, reminiscent of Bubble Bobble game',
		negative='realistic, modern, photorealistic, violent, horror',
		image='styles/game/bubble-bobble.jpg',
	),
	StyleItem(
		id='game_cyberpunk-game',
		name='Game Cyberpunk Game',
		origin='Fooocus',
		positive='cyberpunk game style {prompt} . neon, dystopian, futuristic, digital, vibrant, detailed, high contrast, reminiscent of cyberpunk genre video games',
		negative='historical, natural, rustic, low detailed',
		image='styles/game/cyberpunk-game.jpg',
	),
	StyleItem(
		id='game_fighting-game',
		name='Game Fighting Game',
		origin='Fooocus',
		positive='fighting game style {prompt} . dynamic, vibrant, action-packed, detailed character design, reminiscent of fighting video games',
		negative='peaceful, calm, minimalist, photorealistic',
		image='styles/game/fighting-game.jpg',
	),
	StyleItem(
		id='game_gta',
		name='Game Gta',
		origin='Fooocus',
		positive='GTA-style artwork {prompt} . satirical, exaggerated, pop art style, vibrant colors, iconic characters, action-packed',
		negative='realistic, black and white, low contrast, impressionist, cubist, noisy, blurry, deformed',
		image='styles/game/gta.jpg',
	),
	StyleItem(
		id='game_mario',
		name='Game Mario',
		origin='Fooocus',
		positive='Super Mario style {prompt} . vibrant, cute, cartoony, fantasy, playful, reminiscent of Super Mario series',
		negative='realistic, modern, horror, dystopian, violent',
		image='styles/game/mario.jpg',
	),
	StyleItem(
		id='game_minecraft',
		name='Game Minecraft',
		origin='Fooocus',
		positive='Minecraft style {prompt} . blocky, pixelated, vibrant colors, recognizable characters and objects, game assets',
		negative='smooth, realistic, detailed, photorealistic, noise, blurry, deformed',
		image='styles/game/minecraft.jpg',
	),
	StyleItem(
		id='game_pokemon',
		name='Game Pokemon',
		origin='Fooocus',
		positive='Pokémon style {prompt} . vibrant, cute, anime, fantasy, reminiscent of Pokémon series',
		negative='realistic, modern, horror, dystopian, violent',
		image='styles/game/pokemon.jpg',
	),
	StyleItem(
		id='game_retro-arcade',
		name='Game Retro Arcade',
		origin='Fooocus',
		positive='retro arcade style {prompt} . 8-bit, pixelated, vibrant, classic video game, old school gaming, reminiscent of 80s and 90s arcade games',
		negative='modern, ultra-high resolution, photorealistic, 3D',
		image='styles/game/retro-arcade.jpg',
	),
	StyleItem(
		id='game_retro-game',
		name='Game Retro Game',
		origin='Fooocus',
		positive='retro game art {prompt} . 16-bit, vibrant colors, pixelated, nostalgic, charming, fun',
		negative='realistic, photorealistic, 35mm film, deformed, glitch, low contrast, noisy',
		image='styles/game/retro-game.jpg',
	),
	StyleItem(
		id='game_rpg-fantasy-game',
		name='Game Rpg Fantasy Game',
		origin='Fooocus',
		positive='role-playing game (RPG) style fantasy {prompt} . detailed, vibrant, immersive, reminiscent of high fantasy RPG games',
		negative='sci-fi, modern, urban, futuristic, low detailed',
		image='styles/game/rpg-fantasy-game.jpg',
	),
	StyleItem(
		id='game_strategy-game',
		name='Game Strategy Game',
		origin='Fooocus',
		positive='strategy game style {prompt} . overhead view, detailed map, units, reminiscent of real-time strategy video games',
		negative='first-person view, modern, photorealistic',
		image='styles/game/strategy-game.jpg',
	),
	StyleItem(
		id='game_streetfighter',
		name='Game Streetfighter',
		origin='Fooocus',
		positive='Street Fighter style {prompt} . vibrant, dynamic, arcade, 2D fighting game, highly detailed, reminiscent of Street Fighter series',
		negative='3D, realistic, modern, photorealistic, turn-based strategy',
		image='styles/game/streetfighter.jpg',
	),
	StyleItem(
		id='game_zelda',
		name='Game Zelda',
		origin='Fooocus',
		positive='Legend of Zelda style {prompt} . vibrant, fantasy, detailed, epic, heroic, reminiscent of The Legend of Zelda series',
		negative='sci-fi, modern, realistic, horror',
		image='styles/game/zelda.jpg',
	),
]
