from app.schemas.styles import StyleItem

mre_styles = [
	StyleItem(
		id='mre_cinematic-dynamic',
		name='MRE Cinematic Dynamic',
		origin='Fooocus',
		positive='epic cinematic shot of dynamic {prompt} in motion. main subject of high budget action movie. raw photo, motion blur. best quality, high resolution',
		negative='static, still, motionless, sluggish. drawing, painting, illustration, rendered. low budget. low quality, low resolution',
		image='styles/mre/cinematic-dynamic.jpg',
	),
	StyleItem(
		id='mre_spontaneous-picture',
		name='MRE Spontaneous Picture',
		origin='Fooocus',
		positive='spontaneous picture of {prompt}, taken by talented amateur. best quality, high resolution. magical moment, natural look. simple but good looking',
		negative='overthinked. low quality, low resolution',
		image='styles/mre/spontaneous-picture.jpg',
	),
	StyleItem(
		id='mre_artistic-vision',
		name='MRE Artistic Vision',
		origin='Fooocus',
		positive='powerful artistic vision of {prompt}. breathtaking masterpiece made by great artist. best quality, high resolution',
		negative='insignificant, flawed, made by bad artist. low quality, low resolution',
		image='styles/mre/artistic-vision.jpg',
	),
	StyleItem(
		id='mre_dark-dream',
		name='MRE Dark Dream',
		origin='Fooocus',
		positive='dark and unsettling dream showing {prompt}. best quality, high resolution. created by genius but depressed mad artist. grim beauty',
		negative='naive, cheerful. comfortable, casual, boring, cliche. low quality, low resolution',
		image='styles/mre/dark-dream.jpg',
	),
	StyleItem(
		id='mre_gloomy-art',
		name='MRE Gloomy Art',
		origin='Fooocus',
		positive='astonishing gloomy art made mainly of shadows and lighting, forming {prompt}. masterful usage of lighting, shadows and chiaroscuro. made by black-hearted artist, drawing from darkness. best quality, high resolution',
		negative='low quality, low resolution',
		image='styles/mre/gloomy-art.jpg',
	),
	StyleItem(
		id='mre_bad-dream',
		name='MRE Bad Dream',
		origin='Fooocus',
		positive="picture from really bad dream about terrifying {prompt}, true horror. bone-chilling vision. mad world that shouldn't exist. best quality, high resolution",
		negative='nice dream, pleasant experience. low quality, low resolution',
		image='styles/mre/bad-dream.jpg',
	),
	StyleItem(
		id='mre_underground',
		name='MRE Underground',
		origin='Fooocus',
		positive='uncanny caliginous vision of {prompt}, created by remarkable underground artist. best quality, high resolution. raw and brutal art, careless but impressive style. inspired by darkness and chaos',
		negative='photography, mainstream, civilized. low quality, low resolution',
		image='styles/mre/underground.jpg',
	),
	StyleItem(
		id='mre_surreal-painting',
		name='MRE Surreal Painting',
		origin='Fooocus',
		positive='surreal painting representing strange vision of {prompt}. harmonious madness, synergy with chance. unique artstyle, mindbending art, magical surrealism. best quality, high resolution',
		negative='photography, illustration, drawing. realistic, possible. logical, sane. low quality, low resolution',
		image='styles/mre/surreal-painting.jpg',
	),
	StyleItem(
		id='mre_dynamic-illustration',
		name='MRE Dynamic Illustration',
		origin='Fooocus',
		positive='insanely dynamic illustration of {prompt}. best quality, high resolution. crazy artstyle, careless brushstrokes, emotional and fun',
		negative='photography, realistic. static, still, slow, boring. low quality, low resolution',
		image='styles/mre/dynamic-illustration.jpg',
	),
	StyleItem(
		id='mre_undead-art',
		name='MRE Undead Art',
		origin='Fooocus',
		positive='long forgotten art created by undead artist illustrating {prompt}, tribute to the death and decay. miserable art of the damned. wretched and decaying world. best quality, high resolution',
		negative='alive, playful, living. low quality, low resolution',
		image='styles/mre/undead-art.jpg',
	),
	StyleItem(
		id='mre_elemental-art',
		name='MRE Elemental Art',
		origin='Fooocus',
		positive='art illustrating insane amounts of raging elemental energy turning into {prompt}, avatar of elements. magical surrealism, wizardry. best quality, high resolution',
		negative='photography, realistic, real. low quality, low resolution',
		image='styles/mre/elemental-art.jpg',
	),
	StyleItem(
		id='mre_space-art',
		name='MRE Space Art',
		origin='Fooocus',
		positive='winner of inter-galactic art contest illustrating {prompt}, symbol of the interstellar singularity. best quality, high resolution. artstyle previously unseen in the whole galaxy',
		negative='created by human race, low quality, low resolution',
		image='styles/mre/space-art.jpg',
	),
	StyleItem(
		id='mre_ancient-illustration',
		name='MRE Ancient Illustration',
		origin='Fooocus',
		positive='sublime ancient illustration of {prompt}, predating human civilization. crude and simple, but also surprisingly beautiful artwork, made by genius primeval artist. best quality, high resolution',
		negative='low quality, low resolution',
		image='styles/mre/ancient-illustration.jpg',
	),
	StyleItem(
		id='mre_brave-art',
		name='MRE Brave Art',
		origin='Fooocus',
		positive='brave, shocking, and brutally true art showing {prompt}. inspired by courage and unlimited creativity. truth found in chaos. best quality, high resolution',
		negative='low quality, low resolution',
		image='styles/mre/brave-art.jpg',
	),
	StyleItem(
		id='mre_heroic-fantasy',
		name='MRE Heroic Fantasy',
		origin='Fooocus',
		positive='heroic fantasy painting of {prompt}, in the dangerous fantasy world. airbrush over oil on canvas. best quality, high resolution',
		negative='low quality, low resolution',
		image='styles/mre/heroic-fantasy.jpg',
	),
	StyleItem(
		id='mre_dark-cyberpunk',
		name='MRE Dark Cyberpunk',
		origin='Fooocus',
		positive='dark cyberpunk illustration of brutal {prompt} in a world without hope, ruled by ruthless criminal corporations. best quality, high resolution',
		negative='low quality, low resolution',
		image='styles/mre/dark-cyberpunk.jpg',
	),
	StyleItem(
		id='mre_lyrical-geometry',
		name='MRE Lyrical Geometry',
		origin='Fooocus',
		positive='geometric and lyrical abstraction painting presenting {prompt}. oil on metal. best quality, high resolution',
		negative='photography, realistic, drawing, rendered. low quality, low resolution',
		image='styles/mre/lyrical-geometry.jpg',
	),
	StyleItem(
		id='mre_sumi-e-symbolic',
		name='MRE Sumi E Symbolic',
		origin='Fooocus',
		positive='big long brushstrokes of deep black sumi-e turning into symbolic painting of {prompt}. master level raw art. best quality, high resolution',
		negative='photography, rendered. low quality, low resolution',
		image='styles/mre/sumi-e-symbolic.jpg',
	),
	StyleItem(
		id='mre_sumi-e-detailed',
		name='MRE Sumi E Detailed',
		origin='Fooocus',
		positive='highly detailed black sumi-e painting of {prompt}. in-depth study of perfection, created by a master. best quality, high resolution',
		negative='low quality, low resolution',
		image='styles/mre/sumi-e-detailed.jpg',
	),
	StyleItem(
		id='mre_manga',
		name='MRE Manga',
		origin='Fooocus',
		positive='manga artwork presenting {prompt}. created by japanese manga artist. highly emotional. best quality, high resolution',
		negative='low quality, low resolution',
		image='styles/mre/manga.jpg',
	),
	StyleItem(
		id='mre_anime',
		name='MRE Anime',
		origin='Fooocus',
		positive='anime artwork illustrating {prompt}. created by japanese anime studio. highly emotional. best quality, high resolution',
		negative='low quality, low resolution',
		image='styles/mre/anime.jpg',
	),
	StyleItem(
		id='mre_comic',
		name='MRE Comic',
		origin='Fooocus',
		positive='breathtaking illustration from adult comic book presenting {prompt}. fabulous artwork. best quality, high resolution',
		negative='deformed, ugly, low quality, low resolution',
		image='styles/mre/comic.jpg',
	),
]
